# Default Config: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# Formatting Config: https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/resources/config/config.yml
# Compose Config: https://detekt.dev/docs/introduction/compose/

config:
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Inject', 'Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true

coroutines:
  GlobalCoroutineUsage:
    active: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  DataClassShouldBeImmutable:
    active: true
  MagicNumber:
    ignoreEnums: true
    ignoreAnnotated: ['Composable']
    ignorePropertyDeclaration: true
  SpacingBetweenPackageAndImports:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  WildcardImport:
    active: true
    excludeImports: []

comments:
  UndocumentedPublicClass:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/demoapp/**' ]
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
    searchInProtectedClass: false
  UndocumentedPublicFunction:
    active: true
    # Ignore Jetpack Compose functions annotated with @Preview
    ignoreAnnotated:
      - 'Preview'
    excludes: [ '**/test/**', '**/androidTest/**', '**/demoapp/**' ]
    searchProtectedFunction: false
  UndocumentedPublicProperty:
    active: true
    # TODO - Remove the explicit exclusion of Email.kt once we implement the new REST API
    excludes: [ '**/test/**', '**/androidTest/**', '**/demoapp/**', '**/models/Email.kt' ]
    searchProtectedProperty: false